trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: jobfitscore-secrets
  - name: RESOURCE_GROUP
    value: "jobfitscore-rg"
  - name: LOCATION
    value: "brazilsouth"
  - name: ACI_NAME
    value: "jobfitscore-db"
  - name: ACI_APP_NAME
    value: "jobfitscore-app"
  - name: CONTAINER_IMAGE
    value: "postgres:16-alpine"
  - name: DOCKER_REGISTRY
    value: "index.docker.io"
  - name: DOCKER_IMAGE_NAME
    value: "$(DOCKERHUB_USER)/jobfitscore-app"
  - name: DOCKER_IMAGE_TAG
    value: "$(Build.BuildId)"
  - name: MAVEN_CACHE_FOLDER
    value: "$(Pipeline.Workspace)/.m2/repository"
  - name: MAVEN_OPTS
    value: "-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)"

stages:

# --------------------- Build e Testes ---------------------
- stage: BuildAndTest
  displayName: "Build e Testes"
  jobs:
    - job: BuildTestApp
      displayName: "Build/Testes da Aplicação"
      steps:
        - checkout: self

        - task: AzureCLI@2
          displayName: "Obter IP do PostgreSQL"
          name: GetDBIP
          inputs:
            azureSubscription: "jobfitscore-connection"
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              DB_IP=$(az container show --resource-group $(RESOURCE_GROUP) --name $(ACI_NAME) --query ipAddress.ip -o tsv)
              if [ -z "$DB_IP" ]; then
                echo "Erro: Não foi possível obter DB_IP"
                exit 1
              fi
              echo "DB_IP obtida: $DB_IP"
              echo "##vso[task.setvariable variable=DB_IP;isOutput=true]$DB_IP"

        - task: Cache@2
          displayName: "Cache Maven"
          inputs:
            key: 'maven | "$(Agent.OS)" | pom.xml'
            restoreKeys: |
              maven | "$(Agent.OS)"
              maven
            path: $(MAVEN_CACHE_FOLDER)

        - task: JavaToolInstaller@0
          displayName: "Instalar Java 21"
          inputs:
            versionSpec: "21"
            jdkArchitectureOption: "x64"
            jdkSourceOption: "PreInstalled"

        - task: Maven@4
          displayName: "Build Maven"
          env:
            DB_HOST: $(GetDBIP.DB_IP)
            DB_PORT: "5432"
            DB_NAME: $(DB_NAME)
            DB_USER: $(DB_USER)
            DB_PASSWORD: $(DB_PASSWORD)
            SERVER_PORT: "8080"
          inputs:
            mavenPomFile: "pom.xml"
            goals: "clean package -B"
            mavenOptions: "$(MAVEN_OPTS)"

# --------------------- Build Docker e Push ---------------------
- stage: BuildDocker
  displayName: "Build Docker e Push"
  dependsOn: BuildAndTest
  jobs:
    - job: BuildPushDocker
      displayName: "Build/Push Docker"
      steps:
        - checkout: self

        - task: Cache@2
          displayName: "Cache Docker"
          inputs:
            key: 'docker | "$(Agent.OS)" | dockerfiles/Dockerfile'
            path: $(Pipeline.Workspace)/docker_cache
            restoreKeys: |
              docker | "$(Agent.OS)"

        - script: |
            docker buildx create --name jobfitscore-builder --driver docker-container --use || true
            docker buildx use jobfitscore-builder
          displayName: "Configurar Buildx"

        - script: |
            docker buildx build \
              --cache-from=type=local,src=$(Pipeline.Workspace)/docker_cache \
              --cache-to=type=local,dest=$(Pipeline.Workspace)/docker_cache,mode=max \
              --file dockerfiles/Dockerfile \
              --tag $(DOCKER_IMAGE_NAME):$(DOCKER_IMAGE_TAG) \
              --tag $(DOCKER_IMAGE_NAME):latest \
              --load \
              .
          displayName: "Build Docker Image"

        - task: Docker@2
          displayName: "Login Docker Hub"
          inputs:
            command: login
            containerRegistry: dockerhubConnection

        - script: |
            docker push $(DOCKER_IMAGE_NAME):$(DOCKER_IMAGE_TAG)
            docker push $(DOCKER_IMAGE_NAME):latest
          displayName: "Push Docker"

# --------------------- Deploy em ACI ---------------------
- stage: Deploy
  displayName: "Deploy em Azure Container Instances"
  dependsOn: BuildDocker
  jobs:
    - job: DeployACI
      displayName: "Deploy ACI"
      steps:
        - checkout: none

        - task: AzureCLI@2
          displayName: "Validar DB_IP"
          inputs:
            azureSubscription: "jobfitscore-connection"
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              DB_IP_VALUE=$[ stageDependencies.BuildAndTest.BuildTestApp.outputs['GetDBIP.DB_IP'] ]
              if [ -z "$DB_IP_VALUE" ]; then
                echo "Erro: DB_IP vazia"
                exit 1
              fi
              echo "DB_IP: $DB_IP_VALUE"

        - task: AzureCLI@2
          displayName: "Deploy App no ACI"
          inputs:
            azureSubscription: "jobfitscore-connection"
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              set -e
              DB_IP_VALUE=$[ stageDependencies.BuildAndTest.BuildTestApp.outputs['GetDBIP.DB_IP'] ]
              DOCKER_USER=$(DOCKERHUB_USER)
              DOCKER_PASS=$(DOCKERHUB_PASSWORD)
              DB_PASSWORD=$(DB_PASSWORD)

              echo "Deploy da aplicação..."

              az container delete \
                --resource-group $(RESOURCE_GROUP) \
                --name $(ACI_APP_NAME) \
                --yes >/dev/null 2>&1 || true

              sleep 5

              az container create \
                --resource-group $(RESOURCE_GROUP) \
                --name $(ACI_APP_NAME) \
                --image "$(DOCKER_IMAGE_NAME):$(DOCKER_IMAGE_TAG)" \
                --ports 8080 \
                --os-type Linux \
                --cpu 1 --memory 1.5 \
                --dns-name-label "jobfitscore-app" \
                --ip-address public \
                --environment-variables \
                  DB_HOST="$DB_IP_VALUE" \
                  DB_PORT="5432" \
                  DB_NAME="$(DB_NAME)" \
                  DB_USER="$(DB_USER)" \
                  DB_PASSWORD="$DB_PASSWORD" \
                  SERVER_PORT="8080" \
                --restart-policy Always \
                --registry-login-server $(DOCKER_REGISTRY) \
                --registry-username $DOCKER_USER \
                --registry-password $DOCKER_PASS

              sleep 10

              APP_FQDN=$(az container show --resource-group $(RESOURCE_GROUP) --name $(ACI_APP_NAME) --query ipAddress.fqdn -o tsv)
              echo "URL: http://$APP_FQDN:8080"
              echo "##vso[task.setvariable variable=APP_URL]http://$APP_FQDN:8080"
