trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: jobfitscore-secrets

  - name: RESOURCE_GROUP
    value: "gs-jobfitscore"

  - name: ACI_APP_NAME
    value: "jobfitscore-app"

  - name: DOCKER_IMAGE_NAME
    value: "$(DOCKERHUB_USER)/jobfitscore-app"

  - name: DOCKER_IMAGE_TAG
    value: "$(Build.BuildId)"

  - name: MAVEN_CACHE_FOLDER
    value: "$(Pipeline.Workspace)/.m2/repository"

  - name: MAVEN_OPTS
    value: "-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)"

stages:
# =====================================================================
# 1. BUILD E TESTES
# =====================================================================
- stage: BuildAndTest
  displayName: "Build e Testes"
  jobs:
    - job: BuildTestApp
      steps:
        - checkout: self

        - task: Cache@2
          displayName: "Cache Maven"
          inputs:
            key: 'maven | "$(Agent.OS)" | pom.xml'
            restoreKeys: |
              maven | "$(Agent.OS)"
              maven
            path: $(MAVEN_CACHE_FOLDER)

        - task: JavaToolInstaller@0
          displayName: "Instalar Java 21"
          inputs:
            versionSpec: "21"

        - task: Maven@4
          displayName: "Build Maven"
          env:
            DB_HOST: $(DB_IP)
            DB_PORT: $(DB_PORT)
            DB_NAME: $(DB_NAME)
            DB_USER: $(DB_USER)
            DB_PASSWORD: $(DB_PASSWORD)
            SERVER_PORT: "8080"
          inputs:
            mavenPomFile: "pom.xml"
            goals: "clean package -B"
            mavenOptions: "$(MAVEN_OPTS)"

# =====================================================================
# 2. BUILD DOCKER + PUSH
# =====================================================================
- stage: BuildDocker
  displayName: "Build Docker e Push"
  dependsOn: BuildAndTest
  jobs:
    - job: BuildPushDocker
      steps:
        - checkout: self

        - task: Cache@2
          displayName: "Cache Docker"
          inputs:
            key: 'docker | "$(Agent.OS)" | dockerfiles/Dockerfile'
            path: $(Pipeline.Workspace)/docker_cache
            restoreKeys: |
              docker | "$(Agent.OS)"

        - script: |
            docker buildx create --name jobfitscore-builder --driver docker-container --use || true
          displayName: "Configurar Buildx"

        - script: |
            docker buildx build \
              --cache-from=type=local,src=$(Pipeline.Workspace)/docker_cache \
              --cache-to=type=local,dest=$(Pipeline.Workspace)/docker_cache,mode=max \
              --file dockerfiles/Dockerfile \
              --tag $(DOCKER_IMAGE_NAME):$(DOCKER_IMAGE_TAG) \
              --tag $(DOCKER_IMAGE_NAME):latest \
              --load \
              .
          displayName: "Build Docker"

        - task: Docker@2
          displayName: "Login Docker Hub"
          inputs:
            command: login
            containerRegistry: dockerhubConnection

        - script: |
            docker push $(DOCKER_IMAGE_NAME):$(DOCKER_IMAGE_TAG)
            docker push $(DOCKER_IMAGE_NAME):latest
          displayName: "Push Docker"

# =====================================================================
# 3. DEPLOY
# =====================================================================
- stage: Deploy
  displayName: "Deploy no Azure Container Instances"
  dependsOn: BuildDocker
  jobs:
    - job: DeployACI
      steps:
        - checkout: none

        - task: AzureCLI@2
          displayName: "Deploy App"
          inputs:
            azureSubscription: "jobfitscore-connection"
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              set -e

              echo "Deploy da aplicação..."

              az container delete \
                --resource-group $(RESOURCE_GROUP) \
                --name $(ACI_APP_NAME) \
                --yes >/dev/null 2>&1 || true

              sleep 5

              az container create \
                --resource-group $(RESOURCE_GROUP) \
                --name $(ACI_APP_NAME) \
                --image "$(DOCKER_IMAGE_NAME):$(DOCKER_IMAGE_TAG)" \
                --ports 8080 \
                --dns-name-label "jobfitscore-app" \
                --ip-address public \
                --os-type Linux \
                --cpu 1 --memory 1.5 \
                --environment-variables \
                  DB_HOST="$(DB_IP)" \
                  DB_PORT="$(DB_PORT)" \
                  DB_NAME="$(DB_NAME)" \
                  DB_USER="$(DB_USER)" \
                  DB_PASSWORD="$(DB_PASSWORD)" \
                  SERVER_PORT="8080" \
                --restart-policy Always

              APP_URL=$(az container show \
                --resource-group $(RESOURCE_GROUP) \
                --name $(ACI_APP_NAME) \
                --query "ipAddress.fqdn" -o tsv)

              echo "URL: http://$APP_URL:8080"
