trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: jobfitscore-secrets
  - name: RESOURCE_GROUP
    value: "jobfitscore-rg"
  - name: LOCATION
    value: "brazilsouth"
  - name: ACI_NAME
    value: "jobfitscore-db"
  - name: ACI_APP_NAME
    value: "jobfitscore-app"
  - name: CONTAINER_IMAGE
    value: "postgres:16-alpine"
  - name: ACR_NAME
    value: "jobfitscoreacr"
  - name: ACR_LOGIN_SERVER
    value: "jobfitscoreacr.azurecr.io"
  - name: DOCKER_IMAGE_NAME
    value: "jobfitscore-app"
  - name: DOCKER_IMAGE_TAG
    value: "$(Build.BuildId)"
  - name: MAVEN_CACHE_FOLDER
    value: "$(Pipeline.Workspace)/.m2/repository"
  - name: MAVEN_OPTS
    value: "-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)"
  - name: DOCKER_BUILDKIT
    value: "1"

stages:

# --------------------- Build e Testes ---------------------
- stage: BuildAndTest
  displayName: "Build e Testes"
  jobs:
    - job: BuildTestApp
      displayName: "Build/Testes da Aplicação"
      steps:
        - checkout: self

        - task: AzureCLI@2
          displayName: "Obter IP do PostgreSQL"
          name: GetDBIP
          inputs:
            azureSubscription: "jobfitscore-connection"
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              DB_IP=$(az container show --resource-group $(RESOURCE_GROUP) --name $(ACI_NAME) --query ipAddress.ip -o tsv)
              if [ -z "$DB_IP" ]; then
                echo "Erro: Não foi possível obter DB_IP"
                exit 1
              fi
              echo "DB_IP obtida: $DB_IP"
              echo "##vso[task.setvariable variable=DB_IP;isOutput=true]$DB_IP"

        - task: Cache@2
          displayName: "Cache Maven"
          inputs:
            key: 'maven | "$(Agent.OS)" | pom.xml'
            restoreKeys: |
              maven | "$(Agent.OS)"
              maven
            path: $(MAVEN_CACHE_FOLDER)

        - task: JavaToolInstaller@0
          displayName: "Instalar Java 21"
          inputs:
            versionSpec: "21"
            jdkArchitectureOption: "x64"
            jdkSourceOption: "PreInstalled"

        - task: Maven@4
          displayName: "Build Maven"
          env:
            DB_HOST: $(GetDBIP.DB_IP)
            DB_PORT: "5432"
            DB_NAME: $(DB_NAME)
            DB_USER: $(DB_USER)
            DB_PASSWORD: $(DB_PASSWORD)
            SERVER_PORT: "8080"
          inputs:
            mavenPomFile: "pom.xml"
            goals: "clean package -B"
            mavenOptions: "$(MAVEN_OPTS)"
            publishJUnitResults: false

        - task: PublishTestResults@2
          displayName: "Publicar Resultados dos Testes JUnit"
          condition: succeededOrFailed()
          inputs:
            testResultsFormat: 'JUnit'
            testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
            mergeTestResults: true
            failTaskOnFailedTests: true
            testRunTitle: 'Testes JUnit - JobFitScore'

        - task: CopyFiles@2
          displayName: "Copiar JAR para staging"
          inputs:
            SourceFolder: "$(System.DefaultWorkingDirectory)/target"
            Contents: "*.jar"
            TargetFolder: "$(Build.ArtifactStagingDirectory)"
            
        - task: PublishBuildArtifacts@1
          displayName: "Publicar Artefato JAR"
          inputs:
            PathtoPublish: "$(Build.ArtifactStagingDirectory)"
            ArtifactName: "jobfitscore"
            publishLocation: "Container"

# --------------------- Build Docker e Push para ACR ---------------------
- stage: BuildDocker
  displayName: "Build Docker e Push para ACR"
  dependsOn: BuildAndTest
  jobs:
    - job: BuildPushDocker
      displayName: "Build/Push Docker para ACR"
      steps:
        - checkout: self

        - task: AzureCLI@2
          displayName: "Login no ACR"
          inputs:
            azureSubscription: "jobfitscore-connection"
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              az acr login --name $(ACR_NAME)

        - script: |
            set -e
            
            echo "Habilitando Docker BuildKit..."
            export DOCKER_BUILDKIT=1
            
            CACHE_IMAGE="$(ACR_LOGIN_SERVER)/$(DOCKER_IMAGE_NAME):buildcache"
            
            echo "Tentando puxar imagem de cache..."
            docker pull $CACHE_IMAGE || echo "Cache não encontrado, será criado um novo"
            
            echo "Construindo imagem Docker com cache..."
            docker buildx build \
              --file dockerfiles/Dockerfile \
              --cache-from $CACHE_IMAGE \
              --tag $(ACR_LOGIN_SERVER)/$(DOCKER_IMAGE_NAME):$(DOCKER_IMAGE_TAG) \
              --tag $(ACR_LOGIN_SERVER)/$(DOCKER_IMAGE_NAME):latest \
              --tag $CACHE_IMAGE \
              --build-arg BUILDKIT_INLINE_CACHE=1 \
              --progress=plain \
              .
            
            echo "Build concluído com sucesso!"
          displayName: "Build Docker Image com Cache"
          env:
            DOCKER_BUILDKIT: 1

        - script: |
            set -e
            
            echo "Fazendo push das imagens..."
            docker push $(ACR_LOGIN_SERVER)/$(DOCKER_IMAGE_NAME):$(DOCKER_IMAGE_TAG)
            docker push $(ACR_LOGIN_SERVER)/$(DOCKER_IMAGE_NAME):latest
            docker push $(ACR_LOGIN_SERVER)/$(DOCKER_IMAGE_NAME):buildcache
            
            echo "Push concluído com sucesso!"
          displayName: "Push para ACR (incluindo cache)"

        - script: |
            echo "Limpando imagens Docker locais..."
            docker system prune -af --volumes || true
          displayName: "Limpar Cache Local Docker"
          condition: always()

# --------------------- Deploy ---------------------
- stage: Deploy
  displayName: "Deploy em Azure Container Instances"
  dependsOn: BuildDocker
  jobs:
    - job: DeployACI
      displayName: "Deploy ACI"
      steps:
        - checkout: none

        - task: AzureCLI@2
          displayName: "Obter IP do PostgreSQL para Deploy"
          name: GetDBIPDeploy
          inputs:
            azureSubscription: "jobfitscore-connection"
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              DB_IP=$(az container show --resource-group $(RESOURCE_GROUP) --name $(ACI_NAME) --query ipAddress.ip -o tsv)
              if [ -z "$DB_IP" ]; then
                echo "Erro: Não foi possível obter DB_IP"
                exit 1
              fi
              echo "DB_IP obtida para deploy: $DB_IP"
              echo "##vso[task.setvariable variable=DB_IP_DEPLOY]$DB_IP"

        - task: AzureCLI@2
          displayName: "Deploy App no ACI usando ACR"
          inputs:
            azureSubscription: "jobfitscore-connection"
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              set -e
              
              DB_IP_VALUE="$(DB_IP_DEPLOY)"
              DB_PASSWORD=$(DB_PASSWORD)

              echo "Deploy da aplicação com DB_IP: $DB_IP_VALUE"
              
              if [ -z "$DB_IP_VALUE" ]; then
                echo "Erro: DB_IP_VALUE está vazio!"
                exit 1
              fi

              echo "Obtendo credenciais do ACR..."
              ACR_USERNAME=$(az acr credential show --name $(ACR_NAME) --query username -o tsv)
              ACR_PASSWORD=$(az acr credential show --name $(ACR_NAME) --query passwords[0].value -o tsv)

              echo "Deletando container existente (se houver)..."
              az container delete \
                --resource-group $(RESOURCE_GROUP) \
                --name $(ACI_APP_NAME) \
                --yes >/dev/null 2>&1 || true

              sleep 5

              # Criar container usando imagem do ACR com credenciais
              echo "Criando novo container..."
              az container create \
                --resource-group $(RESOURCE_GROUP) \
                --name $(ACI_APP_NAME) \
                --image "$(ACR_LOGIN_SERVER)/$(DOCKER_IMAGE_NAME):$(DOCKER_IMAGE_TAG)" \
                --ports 8080 \
                --os-type Linux \
                --cpu 1 --memory 1.5 \
                --dns-name-label "jobfitscore-app" \
                --ip-address public \
                --environment-variables \
                  DB_HOST="$DB_IP_VALUE" \
                  DB_PORT="5432" \
                  DB_NAME="$(DB_NAME)" \
                  DB_USER="$(DB_USER)" \
                  DB_PASSWORD="$DB_PASSWORD" \
                  SERVER_PORT="8080" \
                --restart-policy Always \
                --registry-login-server "$(ACR_LOGIN_SERVER)" \
                --registry-username "$ACR_USERNAME" \
                --registry-password "$ACR_PASSWORD"

              sleep 10

              APP_FQDN=$(az container show --resource-group $(RESOURCE_GROUP) --name $(ACI_APP_NAME) --query ipAddress.fqdn -o tsv)
              echo "URL: http://$APP_FQDN:8080"
              echo "##vso[task.setvariable variable=APP_URL]http://$APP_FQDN:8080"